Repository cersluv/Proyecto01_Vehiculo-control-remoto-con-sistema-embebido-via-servidor-web, pull requests merged in 2025-10, with the labels that each got.

#17 Agregar estructura de capas Yocto y archivos de configuración base
  Yocto/conf/bblayers.conf
  Yocto/conf/local.conf
  Yocto/meta-customlayer/conf/layer.conf
  Yocto/meta-customlayer/recipes-gpio/libgpio/libgpio_1.0.bb
  Yocto/meta-webcam/conf/layer.conf
  Yocto/meta-webcam/recipes-multimedia/fswebcam/fswebcam_git.bb
Labels: documentation, library

#18 Subir versión final de server.c con comando de compilación cruzada
  server/server_final.c
Labels: enhancement, server

#19 F005 authentication
  auth/authentication.c
  auth/calcular_hash_admin.c
Labels: enhancement, server

#22 Diseño y construcción de librería propia para el manejo de GPIO con extensión PWM
  libgpio-1.0.tar.gz
  libgpio-1.0/Makefile.am
  libgpio-1.0/Makefile.in
  libgpio-1.0/aclocal.m4
  libgpio-1.0/build/ar-lib
  libgpio-1.0/build/compile
  libgpio-1.0/build/config.guess
  libgpio-1.0/build/config.sub
  libgpio-1.0/build/depcomp
  libgpio-1.0/build/install-sh
  libgpio-1.0/build/ltmain.sh
  libgpio-1.0/build/missing
  libgpio-1.0/config.h.in
  libgpio-1.0/configure
  libgpio-1.0/configure.ac
  libgpio-1.0/include/gpio.h
  libgpio-1.0/include/pwm.h
  libgpio-1.0/lib/Makefile.am
  libgpio-1.0/lib/Makefile.in
  libgpio-1.0/lib/gpio.c
  libgpio-1.0/lib/pwm.c
  libgpio-1.0/m4/libtool.m4
  libgpio-1.0/m4/ltoptions.m4
  libgpio-1.0/m4/ltsugar.m4
  libgpio-1.0/m4/ltversion.m4
  libgpio-1.0/m4/lt~obsolete.m4
  libgpio-1.0/src/Makefile.am
  libgpio-1.0/src/Makefile.in
  libgpio-1.0/src/main.c
Labels: enhancement, library
